name: Check black coding style

on:
  push:

jobs:
  doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Black Check
        uses: psf/black@22.8.0